// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqhpOwyWJbv6hM9UDWdz_eAqbRejJFntQ',
    appId: '1:359495417480:web:d7421859f50770bb6a293d',
    messagingSenderId: '359495417480',
    projectId: 'oonzo-assignment',
    authDomain: 'oonzo-assignment.firebaseapp.com',
    storageBucket: 'oonzo-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNsk74Nt8rkO6I2dIHeFt-SEfH7m29Hc',
    appId: '1:359495417480:android:a146ad6126628af76a293d',
    messagingSenderId: '359495417480',
    projectId: 'oonzo-assignment',
    storageBucket: 'oonzo-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS1hOjOMs6ZNyr_h95LovkT-rxtUzOcck',
    appId: '1:359495417480:ios:c368f5961f3b04e56a293d',
    messagingSenderId: '359495417480',
    projectId: 'oonzo-assignment',
    storageBucket: 'oonzo-assignment.appspot.com',
    iosClientId: '359495417480-idnuo5k1559pj426q48cmv0anta9a0m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.oonzooAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS1hOjOMs6ZNyr_h95LovkT-rxtUzOcck',
    appId: '1:359495417480:ios:c368f5961f3b04e56a293d',
    messagingSenderId: '359495417480',
    projectId: 'oonzo-assignment',
    storageBucket: 'oonzo-assignment.appspot.com',
    iosClientId: '359495417480-idnuo5k1559pj426q48cmv0anta9a0m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.oonzooAssignment',
  );
}
